### PR TITLE
Astro 1527 km input update

### PR DESCRIPTION
**Pull request by NicDominguez**
## Brief Description

Adds the Kobayashi Maru style changes to the input and text area components.

## JIRA Link

[ASTRO-1527](https://rocketcom.atlassian.net/browse/ASTRO-1527)

## Related Issue

[Corresponding LitElement Repo PR](https://github.com/RocketCommunicationsInc/astro-components/pull/155)

## General Notes

A few new rules to cover focus and selection pseudo classes had to be created. All colors were switched to using global theme variables when possible

## Motivation and Context

KM guidance

## Issues and Limitations

I cam across a possible accessibility issue in Chrome. The chrome user-agent styles for input:focus are also adding the rules for input:focus-visible. Usually :focus is for when a user clicks on the input and :focus-visible is for when a user or assistive device tabs into an input. However Chrome has decided to treat them the same which by default puts a very prominent orange outline around the input. Our input:focus styling changes that outline to none in order to show our light blue border upon mouse click. This effectively eliminates the :focus-visible styling and makes it the same as our :focus state. Just something to keep in mind if we want to differentiate between a :focus and :focus-visible state in the future. 

## Types of changes

-   [ ] Bug fix
-   [X] New feature
-   [ ] Breaking change

## Checklist

-   [X] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [X] All new and existing tests passed.

### CODE REVIEW

**Review by markacianfrani — CHANGES_REQUESTED** [review]
Can you run regressions on this? I updated the repo with the latest changes in next from lit. few minor color/size changes it looks like. .rux-input needs font-family applied too, it looks like its using Arial right now. 

Good catch on the focus states too. Do you mind making a ticket for that? I saw something similar on the Tree too I think

**Review by micahjones13 — APPROVED** [review]
Just need the updated regressions passing as per Mark's comment, but other than that looks good.

**Comment by NicDominguez** [comment]
> Can you run regressions on this? I updated the repo with the latest changes in next from lit. few minor color/size changes it looks like. .rux-input needs font-family applied too, it looks like its using Arial right now.
> 
> Good catch on the focus states too. Do you mind making a ticket for that? I saw something similar on the Tree too I think

I had forgotten to style the placeholder text so that was throwing it off and we happened to have a 1px difference in border radius. I'll write up the ticket about the focus states.

**Review by markacianfrani — APPROVED** [review]
perfect!

**Pull request merged**
