### PR TITLE
Fax 1689 pop up testing

### PR DESCRIPTION
**Pull request by Cheshire89**
## Brief Description

fixes for rux-menu-item and rux-popup-menu components

added event listener to the menu to close it when item was selected
removed React style click hook from rux-menu-item in favor of stencil @listen click handler

## JIRA Link

https://rocketcom.atlassian.net/browse/ASTRO-1689

## Issues and Limitations

Follow on spy events for stencil story testing
https://rocketcom.atlassian.net/browse/ASTRO-1812

## Types of changes

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [x] I have added tests to cover my changes.

### CODE REVIEW

**Review by NicDominguez — CHANGES_REQUESTED** [review]
I could be mistaken here but I think the idea for testing was to have separate "form-[component]" pages when we were testing their interaction with native form elements. The pop-up e2e tests should be visiting their own storybook page and testing the interactions there. Would you be able to refactor to have the tests use storybook? I think all you would need to do is point to the rux-icon instead of button and listen for the events on the document if you want to still render the log. Let me know if you want some help making the change, i'd be happy to assist.

**Comment by markacianfrani** [comment]
> I could be mistaken here but I think the idea for testing was to have separate "form-[component]" pages when we were testing their interaction with native form elements. The pop-up e2e tests should be visiting their own storybook page and testing the interactions there. Would you be able to refactor to have the tests use storybook? I think all you would need to do is point to the rux-icon instead of button and listen for the events on the document if you want to still render the log. Let me know if you want some help making the change, i'd be happy to assist. 

We don't necessarily have to use Storybook. It's just an option to avoid having to write out arrange step. 

Is there a better way to test events in Cypress?

**Comment by markacianfrani** [comment]
`should select item and closes menu` and `should open menu add another item and close` fail for me when running in watch mode. They pass when running headless though. can you reproduce that?

**Comment by Cheshire89** [comment]
> > I could be mistaken here but I think the idea for testing was to have separate "form-[component]" pages when we were testing their interaction with native form elements. The pop-up e2e tests should be visiting their own storybook page and testing the interactions there. Would you be able to refactor to have the tests use storybook? I think all you would need to do is point to the rux-icon instead of button and listen for the events on the document if you want to still render the log. Let me know if you want some help making the change, i'd be happy to assist.
> 
> We don't necessarily have to use Storybook. It's just an option to avoid having to write out arrange step.
> 
> Is there a better way to test events in Cypress?

Wed need to extend  cypress to tap into spy events to do event listening on story tests. Felt like it was outside of the ticket scope. I can create a ticket for that

**Review by markacianfrani — APPROVED** [review]

**Comment by markacianfrani** [comment]
> > > I could be mistaken here but I think the idea for testing was to have separate "form-[component]" pages when we were testing their interaction with native form elements. The pop-up e2e tests should be visiting their own storybook page and testing the interactions there. Would you be able to refactor to have the tests use storybook? I think all you would need to do is point to the rux-icon instead of button and listen for the events on the document if you want to still render the log. Let me know if you want some help making the change, i'd be happy to assist.
> > 
> > 
> > We don't necessarily have to use Storybook. It's just an option to avoid having to write out arrange step.
> > Is there a better way to test events in Cypress?
> 
> Wed need to extend cypress to tap into spy events to do event listening on story tests. Felt like it was outside of the ticket scope. I can create a ticket for that

sounds good to me. just post the ticket number here please

**Review by NicDominguez — APPROVED** [review]

**Comment by Cheshire89** [comment]
https://rocketcom.atlassian.net/browse/ASTRO-1812

**Pull request merged**
